title: Agustin Chavez
description: A blog by DBC student.
url: http://chavez1310.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html


social:
   github: chavez1310
   twitter: chavezagustin1
   email: chavez.agustin@outlook.com


